-- MySQL Script generated by MySQL Workbench
-- 06/14/16 14:48:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema REFIT
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema REFIT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `REFIT` DEFAULT CHARACTER SET utf8 ;
USE `REFIT` ;

-- -----------------------------------------------------
-- Table `REFIT`.`IDMapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REFIT`.`IDMapping` (
  `NewID` INT(11) NOT NULL AUTO_INCREMENT,
  `OldID` INT(11) NOT NULL,
  `AltID` CHAR(100) NOT NULL,
  PRIMARY KEY (`NewID`))
ENGINE = InnoDB
AUTO_INCREMENT = 398
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `REFIT`.`houseInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REFIT`.`houseInfo` (
  `houseID` INT(11) NOT NULL,
  `houseName` VARCHAR(25) NULL DEFAULT NULL,
  `houseServer` VARCHAR(25) NULL DEFAULT NULL,
  `lastUpdate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`houseID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `REFIT`.`sensorInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REFIT`.`sensorInfo` (
  `houseID` INT(11) NOT NULL,
  `sensorALTID` VARCHAR(25) NOT NULL,
  `sensorID` TINYINT(4) NULL DEFAULT NULL,
  `sensorName` VARCHAR(25) NULL DEFAULT NULL,
  `sensorCategory` TINYINT(4) NULL DEFAULT NULL,
  `lastUpdate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`houseID`, `sensorALTID`),
  CONSTRAINT `FK_SI`
    FOREIGN KEY (`houseID`)
    REFERENCES `REFIT`.`houseInfo` (`houseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `REFIT`.`powerReadings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REFIT`.`powerReadings` (
  `houseID` INT(11) NOT NULL,
  `sensorALTID` VARCHAR(25) NOT NULL,
  `readingWatts` MEDIUMINT(9) NOT NULL,
  `readingTemperature` TINYINT(4) NOT NULL,
  `serverTime` DATETIME NOT NULL,
  INDEX `SFast` (`houseID` ASC, `sensorALTID` ASC, `serverTime` ASC),
  INDEX `FK_idx` (`houseID` ASC, `sensorALTID` ASC),
  CONSTRAINT `FK_PR`
    FOREIGN KEY (`houseID` , `sensorALTID`)
    REFERENCES `REFIT`.`sensorInfo` (`houseID` , `sensorALTID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `REFIT`.`scriptInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REFIT`.`scriptInfo` (
  `houseID` INT(11) NOT NULL,
  `scriptTime` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`houseID`),
  CONSTRAINT `FK_Script`
    FOREIGN KEY (`houseID`)
    REFERENCES `REFIT`.`houseInfo` (`houseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `REFIT`.`sensorReadings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REFIT`.`sensorReadings` (
  `houseID` INT(11) NOT NULL,
  `sensorALTID` VARCHAR(25) NOT NULL,
  `readingWatts` MEDIUMINT(9) NULL DEFAULT NULL,
  `readingTemperature` TINYINT(4) NULL DEFAULT NULL,
  `readingLight` TINYINT(4) NULL DEFAULT NULL,
  `readingHumidity` TINYINT(4) NULL DEFAULT NULL,
  `readingArmed` TINYINT(4) NULL DEFAULT NULL,
  `readingTripped` TINYINT(4) NULL DEFAULT NULL,
  `readingLastTrip` INT(11) NULL DEFAULT NULL,
  `readingStatus` TINYINT(4) NULL DEFAULT NULL,
  `readingKWH` FLOAT NULL DEFAULT NULL,
  `readingBattery` TINYINT(4) NULL DEFAULT NULL,
  `serverTime` DATETIME NULL DEFAULT NULL,
  INDEX `FK_idx` (`houseID` ASC, `sensorALTID` ASC),
  INDEX `SFast` (`houseID` ASC, `sensorALTID` ASC, `serverTime` ASC),
  CONSTRAINT `FK_SR`
    FOREIGN KEY (`houseID` , `sensorALTID`)
    REFERENCES `REFIT`.`sensorInfo` (`houseID` , `sensorALTID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
